# rcp: BROKER MODULE
# rcp: auto-generated noros foreign broker file
# rcp: do not edit this file

import redis
import json

SERVER_ADDR = "0.0.0.0"
SERVER_PORT = 6379
SERVER_DRDB = 0


class _RedisWrapper:
    def __init__(self, host=SERVER_ADDR, port=SERVER_PORT, db=SERVER_DRDB):
        self._redis = redis.Redis(host=host, port=port, db=db)
        self._redis_pubsub = self._redis.pubsub()

    def subscribe(self, actuators_topics):
        self._redis_pubsub.subscribe(**actuators_topics)
        self._redis_pubsub.run_in_thread(sleep_time=0.01, daemon=True)

    def publish(self, topic, msg):
        return self._redis.publish(topic, msg)


class RedisMiddleware:
    def __init__(self, actuators_topics):
        self._redis_wrapper = _RedisWrapper()
        self._actuators_topics = actuators_topics

    def receive(self):
        self._redis_wrapper.subscribe(self._actuators_topics)

    def send(self, topic, msg):
        msgJson = json.dumps({"topic": topic, "data": msg})
        self._redis_wrapper.publish(topic, msgJson)
